### ISSUE TITLE
프로젝트 기능 구현 질문

### ISSUE THREAD

**Issue by hanasol** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#1]
수도 코드에 부동 소수점의 뺄셈을 진행하는 레이블이 존재하는데, 제 생각에 부동 소수점의 뺄셈은 필요 없다고 판단되면 삭제해도 무방한지 필요 없다고 할지라도 기능을 구현해야 하는지 궁금합니다.

**Comment by ljiwoon** [comment]
> 수도 코드에 부동 소수점의 뺄셈을 진행하는 레이블이 존재하는데, 제 생각에 부동 소수점의 뺄셈은 필요 없다고 판단되면 삭제해도 무방한지 필요 없다고 할지라도 기능을 구현해야 하는지 궁금합니다.

네, 제공해드린 코드에서 메모리 관련 내용을 제외하고는 대부분 수정해도 무방합니다.

**Comment by hanasol** [comment]
감사합니다
