### ISSUE TITLE
구현 방법에 따라 점수 다르게 채점 되나요?

### ISSUE THREAD

**Issue by hj-ta** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#11]
구현을 두가지 방법으로 했는데, 혹시 성능차에 따라 점수가 달리 부여되나요?
bilinear interpolation 공식을 사용해서 구현한 코드의 평가가 더 높은가요?

**Comment by hj-ta** [comment]
공식은 첨부한 사진 속 
수식을 의미하는것 입니다!

![Uploading 수식.png…]()

**Comment by hj-ta** [comment]
공식은 사진 속 수식을 말하는 것입니다!
<img width="502" alt="수식" src="https://github.com/user-attachments/assets/1ad41641-e23f-4f92-9251-ba01bebabf57">

**Comment by ljiwoon** [comment]
채점은 연산 결과로 이루어집니다.
