### ISSUE TITLE
같은 디렉토리에 들어있는데 이렇게 나오는 이유를 모르겠습니다...

### ISSUE THREAD

**Issue by kh-woo** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#3]
![화면 캡처 2024-11-29 034007](https://github.com/user-attachments/assets/073bfd95-bf16-45c7-b2ea-c9cefb9d69fb)

**Comment by ljiwoon** [comment]
해당 문제 확인하여 수정했습니다.
Rev1 - 20241129 버전 확인 바랍니다.
