### ISSUE TITLE
PSNR 관련 질문 드립니다. 

### ISSUE THREAD

**Issue by KH818** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#4]
제가 만든 프로그램을 통해서 PSNR 측정을 해보았는데 PSNR의 수치가 존재하는데, jpg 파일을 열어서 보면 검은 화면만 존재합니다. 코드가 잘못되어 안 만들어진 것인지 혹은 PSNR의 수치가 존재한다면 코드는 정상적으로 도는데 jpg 파일이 제대로 안 만들어지는 것인지 모르겠습니다.

**Comment by ljiwoon** [comment]
> 제가 만든 프로그램을 통해서 PSNR 측정을 해보았는데 PSNR의 수치가 존재하는데, jpg 파일을 열어서 보면 검은 화면만 존재합니다. 코드가 잘못되어 안 만들어진 것인지 혹은 PSNR의 수치가 존재한다면 코드는 정상적으로 도는데 jpg 파일이 제대로 안 만들어지는 것인지 모르겠습니다.

모든 픽셀 값이 0이더라도 PSNR은 계산되는 것이 정상입니다.
