### ISSUE TITLE
입력값은 정수로만 들어오나요?

### ISSUE THREAD

**Issue by Hinoto04** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#5]
현재 downsampled에 있는 txt 내부 값들은 모두 정수를 IEEE 754로 표현해둔 것인데
실수가 들어오는 경우의 수가 없다고 가정하고, 코드를 작성해도 무관한가요?

실수로 들어오는 값이 있다고 가정하였을 때,
부동소수점수로 이를 처리하는 것보다 정수로 변환하여 연산하는 것이
더 작은 코드 크기를 가지고, 더 빠른 속도를 가진다면
평가 기준에서 이는 반영되나요?

**Comment by ljiwoon** [comment]
> 현재 downsampled에 있는 txt 내부 값들은 모두 정수를 IEEE 754로 표현해둔 것인데
> 실수가 들어오는 경우의 수가 없다고 가정하고, 코드를 작성해도 무관한가요?
> 
> 실수로 들어오는 값이 있다고 가정하였을 때,
> 부동소수점수로 이를 처리하는 것보다 정수로 변환하여 연산하는 것이
> 더 작은 코드 크기를 가지고, 더 빠른 속도를 가진다면
> 평가 기준에서 이는 반영되나요?

1. 아니요, 모두 처리할 수 있어야 합니다. 하지만 음수는 입력되지 않을 예정입니다.

2. 정수로 변환하여 연산하면 안되며, 모두 IEEE 754에서의 연산을 이용해 구현해야 합니다.
