### ISSUE TITLE
결과값 저장 시, Big Endian으로 저장해야 하나요?

### ISSUE THREAD

**Issue by Hinoto04** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#7]
hex to image 프로그램이 Little Endian으로 저장된 ieee-754를 인식하지 못하는 문제가 있습니다.

**Comment by Hinoto04** [comment]
조금 무식하긴 한데, 파이썬 파일에서 ieee754_to_float를 다음과 같이 바꾸면 정상작동합니다.

```
def ieee754_to_float(hex_str):
    try:
        temp = ""
        temp += hex_str[6:]
        temp += hex_str[4:6]
        temp += hex_str[2:4]
        temp += hex_str[0:2]
        hex_str = temp
        value = int(hex_str, 16)
        float_value = struct.unpack('!f', struct.pack('!I', value))[0]
        # Clip to 0-255 range
        if float_value < 0:
            float_value = 0
        elif float_value > 255:
            float_value = 255
        return int(float_value)
    except:
        return 0
```

**Comment by jihoonkimtech** [comment]
기존 함수가 Big endian을 기준으로 처리하는데 반해 수업에서는 항상 Little endian 프로세서만 사용해서 이 점이 이상했는데  좋은 내용 공유 감사합니다. 

기존 인자로 들어오는 hex_str을 뒤집어 Little Endian으로 바꿔 적용하니 호환됩니다.

utils/hex-decoder.py 파일을 편집기로 열어 ieee754_to_float 함수의 내용을 위와 같이 변경해한 뒤, bat 파일을 실행하면 잘 작동됩니다.

bat 파일 실행 뒤, 검은색 이미지 파일만 출력되시는 분들은 시도해보시면 크게 도움될 것 같습니다. 아니면 프로젝트 생성 시에 Device를 Big Endian으로 바꾸고 진행해도 무방할 것 같습니다.

**Comment by park092211** [comment]
와 감사합니다
