### ISSUE TITLE
입력값이 양수로만 들어온다 하셨는데, Infinity는 고려해야 하나요?

### ISSUE THREAD

**Issue by Hinoto04** [metr0jw/2024-KWU-Assembly-Programming-Term-Project#8]
이미지 값이라는 전제이기 때문에, Infinity 예외처리가 필요한 지 질문 드립니다.

**Comment by ljiwoon** [comment]
NaN과 infinity는 고려하지 않아도 됩니다.
제안서 pdf 파일의 appendix - 2 참고 바랍니다.
